### ISSUE TITLE
Suggestion: Link to github file.

### ISSUE THREAD

**Issue by srobb1** [obophenotype/pattern-review#1]
It would be handy to have a link github file each pattern. For example, when I was correctly pattern_iri_s It would have been fantastic to link directly to the github file so that I could select the 'edit' button to make my pull request.

Sofia

**Comment by matentzn** [comment]
Fixed https://github.com/obophenotype/pattern-review/commit/198ae2adb31b6595906ae56d77be80a007f635f2
