### ISSUE TITLE
Cannot sign off (or unsign) patterns

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/pattern-review#4]
I'm able to load and run the app, but it seems that the sign off mechanism is broken for me. I tried this on Friday and again today on the same pattern:

abnormallyDecreasedPigmentationOfAnatomicalEntity

and got the same result. I select "Sign" and click on "Submit", and it tells me it's already been submitted: "Already signed off on this one!"  Here's a screen recording from today:

https://www.dropbox.com/s/h5ikfczc1uuar1h/Chris_pattern_review_testing_May_6_2019.mov?dl=0

I thought maybe there would be a time lag between signing off with the app and seeing an update on the overview page. If it did go through successfully (but I just need to wait longer), it would be nice to have some confirmation that it went through. The several attempts I've made have not shown up on 

https://github.com/obophenotype/upheno/pulls

**Comment by matentzn** [comment]
I tried giving you edit rights! Maybe that works!

**Comment by chris-grove** [comment]
OK, works now! Thanks @matentzn
